export enum RepositoriesActionTypes {
  SEARCH_REPOSITORIES_BEGIN = "SEARCH_REPOSITORIES_BEGIN",
  SEARCH_REPOSITORIES_SUCCESS = "SEARCH_REPOSITORIES_SUCCESS",
  SEARCH_REPOSITORIES_FAILED = "SEARCH_REPOSITORIES_FAILED",
}
